### ISSUE TITLE
Keep getting this error on running mvn liquibase:diff

### ISSUE THREAD

**Issue by Abhisek1994Roy** [liquibase/liquibase-hibernate#208] opened 2019-07-23 09:29 UTC
[WARNING] Unknown database: Hibernate
[INFO] Performing Diff on database abhisekroy @ jdbc:postgresql://localhost:5432/shield (Default Schema: public)

Diff Results:
[INFO] Error getting default schema

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-422) by [Unito](https://www.unito.io/learn-more)

**Comment by myin142** [comment] 2019-08-14 09:27
Try the versions I commented on this issue #195

**Comment by DanielFran** [comment] 2019-09-03 12:48
@Abhisek1994Roy Did you try with liquibase 3.8.0 and liquibase-hibernate 3.8?

**Comment by Abhisek1994Roy** [comment] 2019-09-05 10:16
The versions weren't available before. Will try and get back. Thanks. @DanielFran

**Comment by Migsi** [comment] 2019-09-18 13:08
I can confirm this issue. We have a project using java 11, if that might help.
@myin142 I tried those versions, but it keeps failing due to a NPE.

**Comment by myin142** [comment] 2019-09-19 09:18
I am not using Spring Boot in my Project. Maybe there it is different. And I also had problems with Java 11. I always got some kind of exception, but not the NPE.

I will try to get it to run with Spring Boot locally.

**Comment by Abhisek1994Roy** [comment] 2019-09-29 13:56
Still getting this error-  Error setting up or running Liquibase: liquibase.command.CommandExecutionException: java.lang.NullPointerException -> [Help 1]

**Comment by myin142** [comment] 2019-09-29 13:59
I posted in the other issue #195 a possible solution to get the NullPointerException. But after that there is another error. You are probably missing some dependencies for the plugin.

**Comment by filipelautert** [comment] 2024-04-15 17:23
Closing this one as a duplactes https://github.com/liquibase/liquibase-hibernate/issues/195 .

**Closed by filipelautert** 2024-04-15 17:23 UTC
Labels: Hacktoberfest
