### ISSUE TITLE
NullPointerException - at liquibase.diff.output.StandardObjectChangeFilter$Filter.matches(StandardObjectChangeFilter.java:104)

### ISSUE THREAD

**Issue by slany** [liquibase/liquibase-hibernate#108] opened 2016-02-24 11:25 UTC
Hi,

model mapping contains: 
`	@ElementCollection
	@CollectionTable(
			name="EVENT_VAL_MSG_PARAM",
			joinColumns = @JoinColumn(name="EVENT_VAL_MSG__ID") // References parent
	)
	@Column(name="PARAM", nullable=false, length = 100)
	@OrderColumn(name="POS")
	private List<String> msgParams;
}`

If I have included OrderColumn, liquibase diff throws exception:

> [ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.4.2:diff (default) on project tw-data: Error setting up or running Liquibase: liquibase.command.CommandExecutionException: java.lang.NullPointerException -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.liquibase:liquibase-maven-plugin:3.4.2:diff (default) on project tw-data: Error setting up or running Liquibase: liquibase.command.CommandExecutionException: java.lang.NullPointerException
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.plugin.MojoExecutionException: Error setting up or running Liquibase: liquibase.command.CommandExecutionException: java.lang.NullPointerException
> 	at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute(AbstractLiquibaseMojo.java:398)
> 	at org.liquibase.maven.plugins.LiquibaseDatabaseDiff.execute(LiquibaseDatabaseDiff.java:146)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
> 	... 19 more
> Caused by: liquibase.exception.LiquibaseException: liquibase.command.CommandExecutionException: java.lang.NullPointerException
> 	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:211)
> 	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:188)
> 	at org.liquibase.maven.plugins.LiquibaseDatabaseDiff.performLiquibaseTask(LiquibaseDatabaseDiff.java:182)
> 	at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute(AbstractLiquibaseMojo.java:394)
> 	... 22 more
> Caused by: liquibase.command.CommandExecutionException: java.lang.NullPointerException
> 	at liquibase.command.AbstractCommand.execute(AbstractCommand.java:13)
> 	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:209)
> 	... 25 more
> Caused by: java.lang.NullPointerException
> 	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
> 	at java.util.regex.Matcher.reset(Matcher.java:309)
> 	at java.util.regex.Matcher.<init>(Matcher.java:229)
> 	at java.util.regex.Pattern.matcher(Pattern.java:1093)
> 	at liquibase.diff.output.StandardObjectChangeFilter$Filter.matches(StandardObjectChangeFilter.java:104)
> 	at liquibase.diff.output.StandardObjectChangeFilter.include(StandardObjectChangeFilter.java:70)
> 	at liquibase.diff.output.StandardObjectChangeFilter.includeMissing(StandardObjectChangeFilter.java:51)
> 	at liquibase.diff.output.changelog.ChangeGeneratorChain.fixMissing(ChangeGeneratorChain.java:28)
> 	at liquibase.diff.output.changelog.ChangeGeneratorFactory.fixMissing(ChangeGeneratorFactory.java:99)
> 	at liquibase.diff.output.changelog.DiffToChangeLog.generateChangeSets(DiffToChangeLog.java:140)
> 	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:120)
> 	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:76)
> 	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:59)
> 	at liquibase.command.DiffToChangeLogCommand.run(DiffToChangeLogCommand.java:61)
> 	at liquibase.command.AbstractCommand.execute(AbstractCommand.java:8)
> 	... 26 more 

I debugged this problem and I found, that in this case is generate PrimeryIndex object which is without name and this code fails on 
`            if (matches == null) {
                matches = nameMatcher.matcher(object.getName()).matches();
            }`

**... everything works, if this code will be changed to:**
`            if (matches == null) {
                matches = object.getName()!=null && nameMatcher.matcher(object.getName()).matches();
            }`

**I hope, this suggestion for fix is OK.** #

**Comment by nvoxland** [comment] 2016-08-12 21:36
Duplicate of #73 which should be fixed in 3.6 with Liquibase 3.5.2

**Closed by nvoxland** 2016-08-12 21:36 UTC
