### ISSUE TITLE
Duplicated add/drop index SQL statements for adding/removing unique constraints

### ISSUE THREAD

**Issue by syahmiabbas** [liquibase/liquibase-hibernate#500] opened 2023-06-15 09:32 UTC
## Environment
**Liquibase Version:** 4.21.1

**Hibernate-core:** 6.2.4.Final

**Liquibase Integration & Version:** maven 4.22.0 (liquibase-maven-plugin)

**liquibase-hibernate6 version:** 4.22.0

**Operating System Type & Version:** Windows 11

**Database Vendor & Version:** MySQL Server 8.0 with mysql-connector-j version 8.0.33

**Infrastructure Type/Provider:** Local PC (Spring boot), Oracle OpenJDK 20.0.1 and Local MySQL DB

## Description
We've created some indexes using JPA's Index annotation. LB successfully created those indexes in the DB. But when we made a change for the index notation for a composite unique index/unique constraint to a single column it would produce a duplicated statement for the creation.

#### For example if we change from a non-unique index to a unique index:
From:
```
@Entity
@Table(name="house",indexes = {
        @Index(name = "location1_index",columnList = "location1"),
})
```
to this:
```
@Entity
@Table(name="house",indexes = {
        @Index(name = "location1_index",columnList = "location1", unique=true),
})
```
it produces this output:
```
-- liquibase formatted sql

-- changeset s:1686820003215-3
ALTER TABLE house ADD CONSTRAINT location1_index UNIQUE (location1);

-- changeset s:1686820003215-1
ALTER TABLE house DROP KEY location1_index;

-- changeset s:1686820003215-2
ALTER TABLE house ADD CONSTRAINT location1_index UNIQUE (location1);
```

#### An another example if we change from a unique index to a non-unique index:
It produces this output:
```
-- liquibase formatted sql

-- changeset s:1686820351911-3
ALTER TABLE house DROP KEY location1_index;

-- changeset s:1686820351911-1
DROP INDEX location1_index ON house;

-- changeset s:1686820351911-2
CREATE INDEX location1_index ON house(location1);
```

### Steps To Reproduce
Steps we do in our app:

1. Have existing app
2. Add the following entity:
```
package com.liquibase;

import jakarta.persistence.*;

import java.io.Serializable;

@Entity
@Table(name="house",indexes = {
        @Index(name = "location1_index",columnList = "location1"),
})
public class House implements Serializable {
    @Id
    @GeneratedValue
    private Integer id;
    @Column(length = 100)
    private String owner;
    private String location1;

}
```
3. build the app
4. run ```mvn install```
5. run ```mvn liquibase:diff``` 
6. run ```mvn install``` again
7. run ```mvn liquibase:update```
8. Now make the change for the indexes to:
```
@Table(name="house",indexes = {
        @Index(name = "location1_index",columnList = "location1",unique = true),
})
```
9. Run step 3-5 again
10. Now you can check the changelog file and see the above problem

### Actual Behavior
Creates an additional line for the dropping/creating for the index which causes an error when trying to update it to the database
### Expected/Desired Behavior
It should not be creating the additional line above for dropping that causes an error when updating

### Additional Context
Another note I observed was the numbering for the changesets were ordered weirdly, being starting from 3 then 1 then 2
```
-- changeset s:1686820351911-3
ALTER TABLE house DROP KEY location1_index;

-- changeset s:1686820351911-1
DROP INDEX location1_index ON house;

-- changeset s:1686820351911-2
CREATE INDEX location1_index ON house(location1);
```

**Comment by fleboulch** [comment] 2023-08-14 09:25
It seems it's a duplicate of this [one](https://github.com/liquibase/liquibase-hibernate/issues/436)

**Closed** 2024-04-24 12:33 UTC
Labels: TypeBug
