### ISSUE TITLE
Changelog does not generate on changing column size in annotation on Hibernate 5

### ISSUE THREAD

**Issue by KshitijVG** [liquibase/liquibase-hibernate#163] opened 2017-09-11 14:58 UTC
Example - @Column(length = 20) in system, now only change the length to any other number, and try generating the changelog difference. Changelog does not show the changed column size.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-468) by [Unito](https://www.unito.io/learn-more)

**Comment by giovanni-attratto** [comment] 2018-02-27 17:38
This bug is quite important!
Do you have news about it?

**Comment by e-g-hategan** [comment] 2018-12-06 11:03
This is probably related / a duplicate of https://github.com/liquibase/liquibase-hibernate/issues/48

**Comment by StevenMassaro** [comment] 2023-01-11 13:34
This was recently reported in the main liquibase project as well, https://github.com/liquibase/liquibase/issues/2736

**Closed** 2023-01-25 03:48 UTC
Labels: Hacktoberfest, sprint2023-42
