### ISSUE TITLE
Integrator not compatible with Hibernate ORM 5.0.1

### ISSUE THREAD

**Issue by IvanRF** [liquibase/liquibase-hibernate#96] opened 2015-09-24 20:14 UTC
The current Liquibase Hibernate Extension (`liquibase-hibernate4`) **is not compatible** with Hibernate ORM 5.0.1.

Here is the error report: [AbstractMethodError in SessionFactoryImpl](https://hibernate.atlassian.net/browse/HHH-10100)

Steve Ebersole said:
> That line is attempting to call Integrators. I would assume you have Integrators not intended for use with Hibernate 5.0. That contract did change in 5.0 as discussed in the migration guide.

Also mentioned in [Liquibase + Hibernate ORM 5.0](http://stackoverflow.com/questions/32231741/liquibase-hibernate-orm-5-0/)

Here is [Hibernate 5.0 Migration Guide](https://github.com/hibernate/hibernate-orm/blob/5.0/migration-guide.adoc)

**Comment by jdubois** [comment] 2015-10-13 14:21
Hibernate 5.x support would be great! @nvoxland any idea when work will start on supporting it?

**Comment by lluiscanals** [comment] 2016-01-25 09:36
+1 to Hibernate 5.x support!

**Comment by howie** [comment] 2016-02-05 03:12
+1

**Comment by rivergod** [comment] 2016-02-15 14:28
+1

**Comment by zyro23** [comment] 2016-02-18 10:33
+1

**Comment by andrejpetras** [comment] 2016-03-03 19:18
+1

**Comment by charliecooper45** [comment] 2016-04-02 16:29
+1

**Comment by siyb** [comment] 2016-04-07 14:54
+1

**Comment by vrudikov** [comment] 2016-04-08 09:00
+1

**Comment by kflorian** [comment] 2016-05-10 16:11
+1

**Comment by jean-merelis** [comment] 2016-06-03 15:48
I started a lab repository based on liquibase-hibernate to support Hibernate 5.x.
https://github.com/jean-merelis/liquibase-hibernate5

**Comment by lluiscanals** [comment] 2016-06-03 16:02
@jean-merelis :+1: :tada:

**Comment by cbornet** [comment] 2016-07-20 12:19
+1

**Comment by pascalgrimaud** [comment] 2016-07-20 12:59
+1

**Comment by deepu105** [comment] 2016-07-20 13:09
+1

**Comment by alfredorueda** [comment] 2016-07-20 13:20
+1

**Comment by sdoxsee** [comment] 2016-07-20 13:37
+1

**Comment by matlock08** [comment] 2016-07-20 14:50
+1

**Comment by marhan** [comment] 2016-07-20 16:58
+1

**Comment by 7eben** [comment] 2016-07-20 17:29
+1

**Comment by sakhtar1979** [comment] 2016-07-20 18:07
+1

**Comment by cdavid15** [comment] 2016-07-20 19:41
+1

**Comment by cicoub13** [comment] 2016-07-20 21:27
+1

**Comment by mptardy** [comment] 2016-07-21 05:20
+1

**Comment by eddiejaoude** [comment] 2016-07-21 06:32
+10 😁

**Comment by charlvictor** [comment] 2016-07-22 09:39
+1

**Comment by Ari651** [comment] 2016-07-22 16:37
+1

**Comment by thomasoreilly** [comment] 2016-07-29 14:02
+1

**Comment by Cerbis** [comment] 2016-08-01 09:22
+1

**Comment by jean-merelis** [comment] 2016-08-02 17:04
@jdubois Sorry for the delay, I was involved with another project, but I will return to this project in a few days, I am counting on the help of you especially with spring

**Comment by nvoxland** [comment] 2016-08-02 20:20
Sorry, looking through the hibernate issues has been my "next project" for far too long. Part of the problem is that I've not used hibernate in a while and so need to get up to speed on what the problems are. If actual hibernate users are able to send a pull request and/or comment on what should be changed that would be a huge help.

**Comment by rocksfort** [comment] 2016-08-04 08:29
+1 to Hibernate 5 support.
We'd really like to move to Hibernate 5 with our JHipster project.

**Comment by sometxdude** [comment] 2016-08-10 19:53
+1

**Comment by octoroid** [comment] 2016-08-12 08:28
+1

**Comment by yiqingj** [comment] 2016-08-12 17:06
+1

**Comment by CassianoNeves** [comment] 2016-08-30 14:19
+1

**Comment by notflorian** [comment] 2016-08-31 12:07
+1 to Hibernate 5 support also.

**Comment by bobpiece** [comment] 2016-09-05 14:10
+1 (Hibernate  5 support)

**Comment by nvoxland** [comment] 2016-09-08 15:29
I'm nearly done with the hibernate 5 support. Still getting the hibernate:classic url to work passing in a package name. It will depend on 3.5.2 which I'm trying to get out this week, then I can post a RC for the liquibase-hibernate extension.

**Comment by deepu105** [comment] 2016-09-08 16:32
Awesome


Thanks & Regards,
Deepu

**Comment by azizkhani** [comment] 2016-09-15 07:00
+1

**Comment by Kipriz** [comment] 2016-09-15 12:12
@nvoxland Is there any news regarding hibernate 5 support?

**Comment by VovaViter** [comment] 2016-09-15 16:09
+1

**Comment by animator013** [comment] 2016-09-22 12:05
Is there any RC coming in near future ?

**Comment by KerchumA222** [comment] 2016-09-22 19:54
+1

**Comment by nvoxland** [comment] 2016-09-23 17:18
I pushed support for Hibernate 5.2 to the master branch in liquibase-hibernate Hibernate 4 support has been moved to a new hibernate4 branch.

The pre-existing tests are all passing, but I could definitely use some help testing in real environments.

If you don't want to build the liquibase-hibernate code, you can pull the jar from the buildserver at https://liquibase.jira.com/builds/browse/CONTRIB-HBNSNAP3

**Comment by dominic-miglar** [comment] 2016-09-26 09:35
Is the JAR with Hibernate 5 support available in a Maven Repo yet?

**Comment by nvoxland** [comment] 2016-09-26 13:41
Not yet, waiting to get some initial testing in before pushing it up.

**Comment by henri-tremblay** [comment] 2016-09-30 00:27
Some testing on my side. With hibernate 5.2.2.

No problem with running the application and creating/migrating the database so far.

However, the  `liquibase-maven-plugin` hasn't worked yet when using `liquibase:diff`.

What I did so far:
* I've added these dependencies to the plugin. I don't know if they should be included to the plugin or be adde manually by the user
```xml
                    <dependency>
                        <groupId>org.hibernate</groupId>
                        <artifactId>hibernate-core</artifactId>
                        <version>${hibernate.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.hibernate</groupId>
                        <artifactId>hibernate-validator</artifactId>
                        <version>${hibernate.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>javax.el</groupId>
                        <artifactId>el-api</artifactId>
                        <version>2.2</version>
                    </dependency>
```
* If a strategy is used on the plugin configuration, it needs to be updated to the new implicit and physical strategy in hibernate
* Then it is still failing about an error on the second level cache that can't be loaded. I need to investigate.

**Comment by nvoxland** [comment] 2016-09-30 14:05
Good to hear testing is going well so far. Thanks again for the help! Let me know if there is anything you need me to help with

**Comment by henri-tremblay** [comment] 2016-10-04 18:39
I do have an issue. From my debugging, it seems the `liquibase-maven-plugin:diff` is creating an entity manager with a default configuration apart from the dialect. This default (which I found a bit weird) wants a second level cache but specifies no region factory. So it fails.

Any idea?

**Comment by henri-tremblay** [comment] 2016-10-07 19:19
@nvoxland I know why it fails. It fails as soon as you have a `@Cache` on an entity. I can reproduce it in your unit tests. I'll check if I can fix it.

**Comment by nvoxland** [comment] 2016-10-12 21:06
Good find, I merged the pull request in for that. Any other issues people are finding (besides what are already logged as separate issues in this repo)?

**Comment by henri-tremblay** [comment] 2016-10-12 23:40
None on my side

Le 12 oct. 2016 5:07 PM, "Nathan Voxland" <notifications@github.com> a
écrit :

**Comment by nvoxland** [comment] 2016-10-13 19:51
Good to hear. There were a couple other issues reported and/or fixed that I have pushed to master. Could you pull the new changes and double-check that everything looks good. When you say that it is, I'll release the new version.

**Comment by henri-tremblay** [comment] 2016-10-15 11:30
I still have one thing to check and I'll be good to go. Hopefully this
week-end

**Comment by henri-tremblay** [comment] 2016-10-17 18:49
Some bad news that need investigation. All this was tested on MySQL.

* It seems Liquibase fault but between 3.4.2 and 3.5.3, the checksum calculation has changed. Annoying when migrating because you get a checksum error
* Liquibase-hibernate5 will add the hibernate_sequence in the change log on MySQL when doing the `liquibase:diff`
* Using a naming strategy doesn't seem to work (I'm passing the implicit and physical strategy in the URL). I don't get `FK_gsfdgsdfs`, instead I get `FKgsfdgsdfs`

I can provide a demo project featuring these issues is needed.

**Comment by nvoxland** [comment] 2016-10-18 16:25
If you have an example you could attach, that would be great. It would help me see what the problems are.

**Comment by henri-tremblay** [comment] 2016-10-18 16:28
Will do that this afternoon

**Comment by henri-tremblay** [comment] 2016-10-18 16:51
Try with this please: https://github.com/henri-tremblay/finaldemo. We can chat if needed.

**Comment by nvoxland** [comment] 2016-10-19 14:05
Thanks, that's an impressively nice setup for reproducing the issue. I'll take a look a bit during the upcoming day, but will look more tonight.

**Comment by henri-tremblay** [comment] 2016-10-20 13:48
Did you have a look? To prevent loosing time looking at it myself if you
already figured it out.

**Comment by nvoxland** [comment] 2016-10-21 04:21
Sorry I didn't get to it yesterday like I was hoping. Looking now, though.

The checksum issue is related to a fix that went into 3.5.0 that adjusted the checksum logic to no longer include blank lines in csv files used by loadData, to make it more resilient. Unfortunately, that means that anyone that happens to have blank lines in their CSV files will get a validation error because they are now different. 

Your csv files have a trailing newline and so are effected.

While I have a checksum version flag that can disable checking during an upgrade, it running without checksum validation can cause unexpected behavior and the version flag is global so making a more seamless upgrade for some would make a less seamless upgrade for others. I ended up leaving the validation error for people with a newline in their csv files in this case.

The work-around is to either run something like "update databasechangelog set md5sum=null where description like "%loadData%" or add a <validCheckSum>any</validCheckSum> tag to the problem changeset.

Is the csv files you have with the newline something everyone using jhipster will run into? Or is it relatively unique to you?

**Comment by cbornet** [comment] 2016-10-21 05:10
Having changes in changelogs when upgrading Jhipster is quite common and you generally need to revert them anyway if you do it for an already deployed app. So I don't think this is a real issue.

**Comment by cbornet** [comment] 2016-10-21 05:14
Oh, I just understood that it's on the checksum calculation so that's an harder issue. Forget my stupid comment...

**Comment by cbornet** [comment] 2016-10-21 05:17
The csv files are common to any JHipster app btw

**Comment by nvoxland** [comment] 2016-10-21 05:25
Is there a jhipster-level "we are upgrading to a new version" flag where we could update the databasechangelog table to clear out potentially problematic changesets using the update clause I listed above?

**Comment by nvoxland** [comment] 2016-10-21 06:09
I pushed a fix for the sequence showing up in the mysql changelog.

The different-format foreign key (no _ in the name) seems to be a change in how the naming strategies are working in hibernate 4.x vs. 5.x. See http://stackoverflow.com/questions/37062675/hibernate-5-1-x-naming-strategy-backward-compatible-with-hibernate-4-x

The test example is using: hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

which as far as I can tell are being used correctly.

**Comment by henri-tremblay** [comment] 2016-10-21 13:49
Thanks. I'll test the sequence. I'll check for the naming. About the checksum, yes, this is standard Jhipster. But it will also happen to anyone using a csv then.  And having a final endline is quite standard.

So I don't know what to think about it. We will still have to upgrade liquibase but I think a fix accepting the final endline would make everyone's life easier.

**Comment by henri-tremblay** [comment] 2016-10-21 14:10
1- I confirm that if there is no EOF endline in the CSV, the checksum is correcte

**Comment by henri-tremblay** [comment] 2016-10-21 14:16
2- I also confirm that the hibernate_sequence is not re-created. So that's fixed

**Comment by henri-tremblay** [comment] 2016-10-21 19:07
3- Hibernate has changed its naming strategy. I filed an (issue)[https://hibernate.atlassian.net/browse/HHH-11193] to see if that was meant to be. Meanwhile, I have two choices. One is to leave it like that. The other is to add a custom naming strategy in JHipster. Anyhow, there is nothing you can do about it.

**Comment by henri-tremblay** [comment] 2016-10-21 19:08
3- Hibernate has changed its naming strategy. I filed an [issue])https://hibernate.atlassian.net/browse/HHH-11193) to see if that was meant to be. Meanwhile, I have two choices. One is to leave it like that. The other is to add a custom naming strategy in JHipster. Anyhow, there is nothing you can do about it.

**Comment by henri-tremblay** [comment] 2016-10-21 19:10
Bottomline:
1- A possible liquibase fix but not related to liquibase-hibernate
2- Fixed
3- An hibernate issue

I validate that everything is working perfectly. You can release whenever you want.

**Comment by nvoxland** [comment] 2016-10-21 21:25
The whole checksum handling logic is definitely part of my larger changes I'm working on for Liquibase 4 because it isn't flexible enough at this point. 

I do have a version as part of the checksum that I can use to say "this old checksum was computed differently, so just ignore it", but it's a global number so it just makes all the changeSets ignored. The other problem is that when I go into "we can't trust the old checksum" mode, then it breaks the runOnChange logic, doesn't catch actual unexpected changed changeSets, and causes some other similar unexpected behavior for users. Because of that I have to be careful about not changing checksum logic if at all possible, but when we end up needing to we have to decide between making it transparent for people whose checksums changed vs. affecting everyone.  

In this case,  we ended up thinking that when we were adjusting the checksum logic to no longer care about whitespace, the selection of people with CSVs that have empty lines was small enough that it wasn't worth potentially causing problems for everyone else.

If JHipster does have a lot of users with CSV files with a trailing newline, it is probably worth figuring out something to make it more transparent vs. making them add a <validCheckSum> to problem changeSets and/or running the update statement.

I'm looking to see if I can see a good way to handle it in the liquibase code, but it will take a new liquibase release, not just a new liquibase-hibernate release.

**Comment by henri-tremblay** [comment] 2016-10-22 08:12
I will remove the newlines at EOF for future JHipster versions. But in fact, pretty much everyone use a final newline from what I know. So I'm a bit surprised that nobody complained.

Anyway. When do you think you can release liquibase-hibernate?

**Comment by nvoxland** [comment] 2016-10-24 17:03
You don't have to worry about removing the EOF newlines since the liquibase change that caused the problem makes empty newlines now not a part of the checksum. So from now on it doesn't matter if there are newlines at the end or in the middle or anywhere else. Better and more consistent for everyone from now on.

I'll release the new liquibase-hibernate version today.

**Closed by nvoxland** 2016-10-24 17:03 UTC

**Comment by nvoxland** [comment] 2016-10-24 20:38
It has now been released as liquibase-hibernate5 3.6

**Comment by IvanRF** [comment] 2016-10-24 21:41
@nvoxland thank you very much Nathan! I'm glad you could fix this, great work!

**Comment by dpupaza** [comment] 2016-10-24 22:43
@nvoxland awesome work and thanks! Any idea when it will be available on Maven Central?

**Comment by deepu105** [comment] 2016-10-25 18:21
In my opinion if adding/removing newlines to CSV can ease your problem a
bit I think we can do that for Jhipster and advice users who are upgrading
to do the same. Shouldn't be a huge issue.


Thanks & Regards,
Deepu

**Comment by henri-tremblay** [comment] 2016-10-25 18:43
@deepu105 The thing is that for existing users, it will be too late. Because the current checksum was already calculated with spaces. So in fact @nvoxland is right, removing the spaces now won't help. It was "just in case" for later.

**Comment by nvoxland** [comment] 2016-10-26 04:56
It should be working it's way through maven central. I pushed it to sonatype and they mirror it from there.

**Comment by henri-tremblay** [comment] 2016-10-26 15:46
It is available. Since yesterday at least.

Le 26 oct. 2016 12:56 AM, "Nathan Voxland" <notifications@github.com> a
écrit :
