### ISSUE TITLE
diffChangeLog fails with null exception

### ISSUE THREAD

**Issue by gojesandeep** [liquibase/liquibase-hibernate#76] opened 2015-02-19 11:30 UTC
Unexpected error running Liquibase: java.lang.NullPointerException

[ERROR] liquibase - java.lang.NullPointerException
liquibase.exception.LiquibaseException: liquibase.command.CommandExecutionException: java.lang.NullPointerException
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:123) ~[liquibase-core-3.3.2.jar:na]
	at liquibase.integration.commandline.Main.doMigration(Main.java:936) [liquibase-core-3.3.2.jar:na]
	at liquibase.integration.commandline.Main.run(Main.java:175) [liquibase-core-3.3.2.jar:na]
	at liquibase.integration.commandline.Main.main(Main.java:94) [liquibase-core-3.3.2.jar:na]

For more information, use the --logLevel flagCaused by: liquibase.command.CommandExecutionException: java.lang.NullPointerException
	at liquibase.command.AbstractCommand.execute(AbstractCommand.java:13) ~[liquibase-core-3.3.2.jar:na]
	at liquibase.integration.commandline.CommandLineUtils.doDiffToChangeLog(CommandLineUtils.java:121) ~[liquibase-core-3.3.2.jar:na]
	... 3 common frames omitted
Caused by: java.lang.NullPointerException: null
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283) ~[na:1.8.0_31]
	at java.util.regex.Matcher.reset(Matcher.java:309) ~[na:1.8.0_31]
	at java.util.regex.Matcher.<init>(Matcher.java:229) ~[na:1.8.0_31]
	at java.util.regex.Pattern.matcher(Pattern.java:1093) ~[na:1.8.0_31]
	at liquibase.diff.output.StandardObjectChangeFilter$Filter.matches(StandardObjectChangeFilter.java:104) ~[liquibase-core-3.3.2.jar:na]
	at liquibase.diff.output.StandardObjectChangeFilter.include(StandardObjectChangeFilter.java:70) ~[liquibase-core-3.3.2.jar:na]
	at liquibase.diff.output.StandardObjectChangeFilter.includeMissing(StandardObjectChangeFilter.java:51) ~[liquibase-core-3.3.2.jar:na]
	at liquibase.diff.output.changelog.ChangeGeneratorChain.fixMissing(ChangeGeneratorChain.java:28) ~[liquibase-core-3.3.2.jar:na]
	at liquibase.diff.output.changelog.ChangeGeneratorFactory.fixMissing(ChangeGeneratorFactory.java:99) ~[liquibase-core-3.3.2.jar:na]
	at liquibase.diff.output.changelog.DiffToChangeLog.generateChangeSets(DiffToChangeLog.java:145) ~[liquibase-core-3.3.2.jar:na]
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:125) ~[liquibase-core-3.3.2.jar:na]
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:76) ~[liquibase-core-3.3.2.jar:na]
	at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:64) ~[liquibase-core-3.3.2.jar:na]
	at liquibase.command.DiffToChangeLogCommand.run(DiffToChangeLogCommand.java:61) ~[liquibase-core-3.3.2.jar:na]
	at liquibase.command.AbstractCommand.execute(AbstractCommand.java:8) ~[liquibase-core-3.3.2.jar:na]
	... 4 common frames omitted

:liquibaseDiffChangelog FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':liquibaseDiffChangelog'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Environment : Mac OSX 10.10
DB Postgres 9.3.5.2 
Java 8

**Comment by dejewi** [comment] 2015-02-25 13:22
I have the same problem.

**Comment by seiter** [comment] 2015-02-27 02:03
Same issue here (JDK, notice that if I remove unique=true things work fine. In other words going from example 1. to example 2. below 'fixes' the problem.

1. @Column( name = "job_name", nullable = false, unique = true, length = 100 ) 
2. @Column( name = "job_name", nullable = false, length = 100 )

**Comment by svennela** [comment] 2015-04-09 03:44
@seiter Same here.. unique = true is causing and also 

 @ManyToMany
	    @JoinTable(
	            name = "INVITE_ROLE",
	            joinColumns = {@JoinColumn(name = "INVITE_ID")},
	            inverseJoinColumns = {@JoinColumn(name = "ROLE_ID")})

**Comment by oneillsoftware** [comment] 2015-06-08 15:54
Hi, I am experiencing the same problem when attempting to exclude UniqueConstraints.
Has anyone been able to find a resolution/work around for this?
Thanks.

**Comment by evesun** [comment] 2015-07-27 02:01
@OneToMany JoinTable got same issue, this line in the log  (liquibase:diff) may be related:

"Found unique constraint null MY_JOINTABLE(col_id)"

**Comment by nDija** [comment] 2015-08-05 07:20
This exception occurs from the 3.3.2 -> 3.3.5 version no problem with 3.3.1

**Comment by nvoxland** [comment] 2016-08-10 19:55
Appears to be a duplicate of #73 and not reproducable in the Liquibase 3.5.1 + liquibase-hibernate 3.6 code which should be released in the next week or so.

**Closed by nvoxland** 2016-08-10 19:55 UTC
